defaults: &defaults
  working_directory: /go/src/github.com/mstrzele/watchman
  docker:
    - image: circleci/golang:1.9

version: 2
jobs:
  lint:
    <<: *defaults
    steps:
      - run:
          command: curl https://glide.sh/get | sh
      - checkout
      - run: glide i -v
      - persist_to_workspace:
          root: vendor
          paths:
            - "*"
      - run: go install
      - run:
          command: |
            go get -u github.com/alecthomas/gometalinter
            gometalinter --install
      - run:
          command: gometalinter --deadline=5m --errors $(glide novendor)
  build:
    <<: *defaults
    steps:
      - run:
          command: go get github.com/mitchellh/gox
      - checkout
      - attach_workspace:
          at: vendor
      - run: gox -osarch "darwin/amd64 linux/amd64" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"
      - persist_to_workspace:
          root: dist
          paths:
            - watchman_darwin_amd64
            - watchman_linux_amd64

  deploy:
    <<: *defaults
    steps:
      - run:
          command: go get -u github.com/tcnksm/ghr
      - checkout

      - attach_workspace:
          at: dist

      - run:
          command: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` dist/

workflows:
  version: 2
  lint-build-and-deploy:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
